# Generated by Django 4.0.2 on 2022-03-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_rollnumber', models.IntegerField()),
                ('student_address', models.CharField(max_length=50)),
                ('student_joining', models.DateField()),
            ],
        ),
    ]
