# Generated by Django 4.0.2 on 2022-03-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students_detail',
            old_name='student_board',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='students_detail',
            old_name='student_comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='students_detail',
            old_name='student_date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='students_detail',
            old_name='student_date_of_joining',
            new_name='doj',
        ),
        migrations.RenameField(
            model_name='students_detail',
            old_name='student_father_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='students_detail',
            old_name='student_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='students_detail',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='students_detail',
            old_name='student_class',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='students_detail',
            old_name='student_phone_number',
            new_name='ramt',
        ),
        migrations.RenameField(
            model_name='students_detail',
            old_name='student_receipt_amount',
            new_name='rnum',
        ),
        migrations.RenameField(
            model_name='students_detail',
            old_name='student_receipt_number',
            new_name='sclass',
        ),
    ]
